### PR TITLE
Added Day 5 demo day OG-USA blog post and image

### PR DESCRIPTION
**Pull request by rickecon**
This PR adds the Day 5 Demo Day blog post for the "How to Use OG-USA" demo day (Jan. 11, 2021). Thanks @MaxGhenis  for the help. I do have some questions. 

1. In the blog post, I add the OG-USA logo image (`OG-USA_logo_long.png`) at the top using the command ``. However, I don't have access to the `pslmodels.org/imgs/` folder. So I just placed that image in the `images` folder in the `blogs` repository. Does the GitHub action automatically add new images to the `pslmodels.org/imgs/` folder?
2. Why is there a one-space indent for much of the text of the post? Is that important for the fastpages formatting? If not, I recommend no indent.

### CODE REVIEW

**Comment by rickecon** [comment]
OK @MaxGhenis. I merged in your changes to my branch, I added some small updates to the blog post text, and I added `.DS_Store` to the `.gitignore` because I saw that come up in my `git status`. This is ready to go as soon as all the checks pass.

**Comment by MaxGhenis** [comment]
The image is no longer in the PR, so it's not loading. The `new_post.md` also shouldn't be deleted. Could you add these back? (Sorry if I did something wrong in my PR to make them show up.)

**Comment by rickecon** [comment]
@MaxGhenis. Added the logo back. Give me two minutes to add `new_post.md` back.

**Comment by rickecon** [comment]
@MaxGhenis. There. Everything should be in order now.

**Pull request merged**
