### PR TITLE
DC Workshop blog post

### PR DESCRIPTION
**Pull request by rickecon**
This PR creates a blog post for the PSL Washington, DC Workshop for March 25, 2022.

cc: @jdebacker

### CODE REVIEW

**Comment by rickecon** [comment]
@jdebacker. You'll notice that I put you as the author of this post. I think that is the right thing. I just copied the content from the e-mail invite you sent out.

**Comment by jdebacker** [comment]
Preview:
Screen Shot 2022-03-02 at 9 24 33 AM

**Comment by jdebacker** [comment]
@rickecon Just opened a PR to your branch to fix some formatting.  Thanks for putting this here.

**Comment by rickecon** [comment]
@jdebacker. Some items.
* Yes. The PSL image at the top of the post is too big. Let me add something that combines the PSL logo with the MLK library image and makes both of them smaller.
* It is weird that in the rendering, the bullet points in the schedule don't show up.

I will make changes here. But I will also be looking for any PRs from you.

**Comment by rickecon** [comment]
@jdebacker. I don't know how to render the site on a local server on my machine. So I can't tell if the change I made to the image is too small or if it is still too big. But I combined the PSL image and the library image into one line. The image is 2150 x 500 pixels. I can change the size if it is off when it renders. The bullet points should be fine though.

**Comment by jdebacker** [comment]
To render follow instructions in the README at [PSLmodels/blog](https://github.com/PSLmodels/blog).  This essentially amounts to (1) make sure Docker is running and (2) run `make server` from the `./blog` directory.

I will say that the locally rendered page often lacks some formatting that shows up when this is compiled and served on GH pages.  You might use [this post](http://blog.pslmodels.org/2021-year-in-review) to see how the PSL image sizes.

**Comment by rickecon** [comment]
@jdebacker. Here is the preview. I changed the filename and, therefore, the date. I updated some bolding. And I think the picture looks good. **NOTE:** I did not manually make the change to line 10 of the `settings.ini` file, which change is was to remove the `baseurl = /blog` to just blank `baseurl =`. This must have been some update when I ran the `make server` command from the command line. Let me know if you want me to fix that so there is no change.

BlogScreenShot

**Comment by rickecon** [comment]
@jdebacker. I reverted the `settings.ini` to its original form (almost).

**Comment by jdebacker** [comment]
@rickecon - ready for merge?

**Comment by jdebacker** [comment]
Thanks @rickecon, merged.

**Pull request merged**
